name: Wake up bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      continue-on-error: true
      uses: wei/curl@master
      with:
        args: https://DKOKbotRe.himagenjithiku.repl.co
